window.onerror=function(m,s,l){var d=document.createElement('div');d.style.cssText='position:fixed;top:0;left:0;right:0;background:#b71c1c;color:#fff;padding:10px;font:12px monospace;z-index:99999;direction:ltr';d.textContent='JS ERROR: '+m+' @line '+l;(document.body||document.documentElement).appendChild(d)};
var $=function(s){return document.querySelector(s)},$$=function(s){return[].slice.call(document.querySelectorAll(s))};
function D(k,d){try{var v=JSON.parse(localStorage.getItem(k));return v==null?d:v}catch(e){return d}}
function SV(k,v){localStorage.setItem(k,JSON.stringify(v))}
function fa(s){return String(s).replace(/\d/g,function(d){return'۰۱۲۳۴۵۶۷۸۹'[d]})}
function fmt(n){return fa(Number(n\vert{}\vert{}0).toLocaleString('en-US'))}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function today(){return new Date().toISOString().slice(0,10)}
function now(){return new Date().toTimeString().slice(0,5)}
function toast(m,e){var t=document.createElement('div');t.className='toast'+(e?' error':'');t.textContent=m;$('#tw').appendChild(t);requestAnimationFrame(function(){t.classList.add('show')});setTimeout(function(){t.classList.remove('show');setTimeout(function(){t.remove()},350)},3000)}
function hsh(t){return crypto.subtle.digest('SHA-256',new TextEncoder().encode(t)).then(function(b){return[].map.call(new Uint8Array(b),function(x){return('0'+x.toString(16)).slice(-2)}).join('')})}
var S={user:null,view:'dash'};
var ROLES={admin:['مدیر کل','👑'],factory:['مدیر کارخانه','🧭'],supervisor:['مسئول شیفت','🛡️'],operator:['اپراتور','👷'],warehouse:['انباردار','📦'],finance:['مالی','💰'],maint:['تعمیرکار','🔧'],viewer:['ناظر','👁️']};
var ACC={op:['admin','factory','supervisor','operator'],wh:['admin','factory','warehouse'],fin:['admin','factory','finance'],mt:['admin','factory','maint'],ad:['admin']};
var A={dash:'all',flow:'all',batch:'op',log:'op',buy:'wh',inv:'wh',sales:'fin',fin:'fin',tm:'mt',users:'ad',settings:'ad'};
var MENU=[['🏠 اصلی',[['dash','📊 داشبورد'],['flow','⚡ جریان فرآیند']]],['🔥 پخت و تولید',[['batch','🔥 Batch و چرخه پخت'],['log','🕐 ثبت ساعتی']]],['📦 عملیات و انبار',[['buy','🛒 خرید مواد'],['inv','📦 انبار سه‌بخشی']]],['💰 مالی و فروش',[['sales','🧾 فروش'],['fin','💳 امور مالی']]],['🔧 پشتیبانی',[['tm','🔧 تعمیرات']]],['⚙️ مدیریت',[['users','👥 کاربران و نقش‌ها'],['settings','⚙️ تنظیمات و SOP']]]];
function can(id){var a=A[id];return a=='all'\vert{}\vert{}ACC[a].indexOf(S.user.role)>=0}
function head(t,s){return'<div class="vhead"><h2>'+t+'</h2><p>'+s+'</p></div>'}
var mode='login';
function tabUI(m){mode=m;$('#tLogin').classList.toggle('on',m=='login');$('#tReg').classList.toggle('on',m!='login');$('#gName').classList.toggle('hidden',m!='register');$('#gPass2').classList.toggle('hidden',m!='register');$('#goBtn').textContent=m=='login'?'ورود به سامانه':'ایجاد حساب';['eE','eP','eP2','eTop'].forEach(function(i){$('#'+i).textContent=''})}
$('#tLogin').onclick=function(){tabUI('login')};$('#tReg').onclick=function(){tabUI('register')};
$('#goBtn').onclick=function(){var em=$('#qEmail').value.trim().toLowerCase(),p=$('#qPass').value,ok=true;function E(i,m){$('#'+i).textContent=m;if(m)ok=false}E('eE',/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(em)?'':'ایمیل معتبر نیست.');E('eP',p.length<6?'رمز حداقل ۶ کاراکتر.':'');if(mode=='register'&&$('#qPass2').value!==p)E('eP2','تکرار رمز مطابقت ندارد.');if(!ok)return;var us=D('pp_users',[]);
hsh(p).then(function(h){
if(mode=='register'){if(us.some(function(x){return x.email===em})){$('#eE').textContent='این ایمیل قبلاً ثبت شده.';return}var role=us.length?'viewer':'admin';var u={name:$('#qName').value.trim()\vert{}\vert{}em.split('@')[0],email:em,hash:h,role:role};us.push(u);SV('pp_users',us);localStorage.setItem('pp_session',em);start(u);toast(role=='admin'?'شما مدیر کل هستید 👑':'ثبت‌نام شدید؛ مدیر نقش شما را تعیین می‌کند.')}
else{var f=null;for(var i=0;i<us.length;i++){if(us[i].email===em&&us[i].hash===h){f=us[i];break}}if(!f){$('#eTop').textContent='ایمیل یا رمز اشتباه است.';return}localStorage.setItem('pp_session',em);start(f);toast('خوش آمدید '+f.name)}})};
$('#outBtn').onclick=function(){localStorage.removeItem('pp_session');location.reload()};
function start(u){if(!ROLES[u.role])u.role='viewer';S.user=u;$('#gate').classList.add('hidden');$('#app').classList.remove('hidden');$('#uName').textContent=u.name;$('#uIcon').textContent=ROLES[u.role][1];$('#uRole').textContent=ROLES[u.role][1]+' '+ROLES[u.role][0];renderAside();go('dash')}
function renderAside(){$('#aside').innerHTML=MENU.map(function(g){var ok=g[1].filter(function(i){return can(i[0])});return ok.length?'<div class="grp"><h4>'+g[0]+'</h4>'+ok.map(function(i){return'<button class="sitem" data-v="'+i[0]+'">'+i[1]+'</button>'}).join('')+'</div>':''}).join('');$$('#aside .sitem').forEach(function(b){b.onclick=function(){go(b.getAttribute('data-v'))}})}
var RENDER={};
function go(id){S.view=id;$$('#aside .sitem').forEach(function(b){b.classList.toggle('on',b.getAttribute('data-v')===id)});RENDER[id]()}
RENDER.flow=function(){var F=[['🛒','خرید'],['⚖️','توزین'],['🧰','آماده‌سازی'],['📋','چک‌لیست'],['▶️','Start'],['📈','ثبت ساعتی'],['⚠️','بازه بحرانی'],['🔥','Cracking'],['🛢','روغن‌گیری'],['⏹','خاموشی'],['❄️','Cooling'],['📤','تخلیه'],['🧾','ثبت خروجی'],['💰','فروش'],['📊','سود']];$('#main').innerHTML=head('جریان کامل فرآیند','از خرید تا فروش و سود')+'<div class="panel"><div class="flow">'+F.map(function(f,i){return'<div class="fs"><div class="fi" style="animation-delay:'+(i*.15)+'s">'+f[0]+'</div><span>'+f[1]+'</span></div>'+(i<F.length-1?'<div class="far">➜</div>':'')}).join('')+'</div></div>'};
RENDER.dash=function(){
var bs=D('pp_batches',[]),act=bs.filter(function(b){return b.st!=='done'}).length;
var oil=bs.reduce(function(s,b){return s+(b.st==='done'?(+b.o2\vert{}\vert{}0):0)},0);
var fin=D('pp_fin',[]),inc=fin.reduce(function(s,f){return s+(f.t==='in'?+f.a:0)},0),exp=fin.reduce(function(s,f){return s+(f.t==='out'?+f.a:0)},0);
var rec=D('pp_sales',[]).reduce(function(s,x){return s+(+x.q*+x.p-+x.paid)},0);
var low=D('pp_inv',[]).filter(function(i){return+i.q<+i.m}).length;
$('#main').innerHTML=head('داشبورد','نقش شما: '+ROLES[S.user.role][0])+'<div class="kpis">'
+'<div class="kpi k-blue"><i>🔥</i><div><h5>Batch در جریان</h5><div class="v">'+fa(act)+'</div></div></div>'
+'<div class="kpi k-pur"><i>🛢</i><div><h5>روغن تولیدی (لیتر)</h5><div class="v">'+fmt(oil)+'</div></div></div>'
+'<div class="kpi k-green"><i>💰</i><div><h5>درآمد (ریال)</h5><div class="v">'+fmt(inc)+'</div></div></div>'
+'<div class="kpi k-org"><i>📉</i><div><h5>هزینه (ریال)</h5><div class="v">'+fmt(exp)+'</div></div></div>'
+'<div class="kpi '+(rec>0?'k-red':'k-green')+'"><i>🧾</i><div><h5>مطالبات مانده</h5><div class="v">'+fmt(rec)+'</div></div></div>'
+'<div class="kpi '+(low?'k-red':'k-blue')+'"><i>📦</i><div><h5>هشدار انبار</h5><div class="v">'+fa(low)+'</div></div></div></div>'
+'<div class="panel"><h3>دسترسی نقش شما</h3><div style="font-size:13px;line-height:2.2">'+(S.user.role=='operator'?'👩‍🏭 اپراتور: داشبورد + پخت + ثبت ساعتی — مالی و انبار مخفی.':S.user.role=='warehouse'?'📦 انباردار: خرید + انبار — مالی مخفی.':S.user.role=='admin'?'👑 مدیر کل: دسترسی کامل + تعیین نقش کاربران.':'دسترسی‌های شما در منو نمایش داده شده.')+'</div></div>'};
RENDER.buy=function(){var mats=D('pp_mat',['لاستیک','پلاستیک','روغن سوخته','گریس سوخته']),arr=D('pp_buy',[]);
var rows=arr.map(function(r){return'<tr><td>'+esc(r.d)+'</td><td>'+esc(r.s)+'</td><td>'+esc(r.m)+'</td><td dir="ltr">'+fa(r.w)+' kg</td><td dir="ltr">'+fmt(+r.p+ +r.t)+'</td><td class="warnc" dir="ltr">'+fa(Math.round((+r.p+ +r.t)/r.w))+'</td></tr>'}).join('');
$('#main').innerHTML=head('خرید مواد اولیه','خرید → موجودی انبار + هزینه مالی')+'<div class="panel"><h3>ثبت خرید</h3><div class="fgrid"><input class="inp" type="date" id="bD" value="'+today()+'"><input class="inp" id="bSup" placeholder="تأمین‌کننده"><select class="inp" id="bM">'+mats.map(function(m){return'<option>'+esc(m)+'</option>'}).join('')+'</select></div><div class="fgrid"><input class="inp" type="number" id="bW" placeholder="وزن (kg)"><input class="inp" type="number" id="bP" placeholder="قیمت کل (ریال)"><input class="inp" type="number" id="bT" placeholder="حمل+تخلیه (ریال)"></div><button class="fbtn" id="bAdd">ثبت خرید</button></div><div class="panel"><h3>خریدها ('+fa(arr.length)+')</h3><div class="tbw"><table><tr><th>تاریخ</th><th>تأمین‌کننده</th><th>ماده</th><th>وزن</th><th>هزینه</th><th>هر کیلو</th></tr>'+rows+'</table></div></div>';
$('#bAdd').onclick=function(){var w=+$('#bW').value,p=+$('#bP').value;if(!w\vert{}\vert{}!p){toast('وزن و قیمت را وارد کن.',1);return}var r={d:$('#bD').value,s:$('#bSup').value.trim()\vert{}\vert{}'—',m:$('#bM').value,w:w,p:p,t:+$('#bT').value\vert{}\vert{}0};arr.push(r);SV('pp_buy',arr);
var inv=D('pp_inv',[]),f2=null;for(var z=0;z<inv.length;z++){if(inv[z].c==='raw'&&inv[z].n===r.m){f2=inv[z];break}}if(f2)f2.q=+f2.q+w;else inv.push({c:'raw',n:r.m,q:w,u:'kg',m:1000});SV('pp_inv',inv);
var fin=D('pp_fin',[]);fin.push({d:r.d,t:'out',de:'خرید '+r.m+' — '+r.s,a:r.p+r.t});SV('pp_fin',fin);toast('خرید ثبت شد ✅');RENDER.buy()}};
RENDER.inv=function(){var CAT={raw:'🌿 مواد اولیه',prod:'🛢 محصولات',part:'🔧 قطعات'},cat='raw';
function draw(){var inv=D('pp_inv',[]);
var rows=inv.filter(function(i){return i.c===cat}).map(function(i){var low=+i.q<+i.m;return'<tr><td>'+esc(i.n)+'</td><td dir="ltr">'+fmt(i.q)+'</td><td>'+esc(i.u)+'</td><td dir="ltr">'+fmt(i.m)+'</td><td class="'+(low?'badc':'okc')+'">'+(low?'کمبود!':'موجود')+'</td></tr>'}).join('');
$('#main').innerHTML=head('انبار سه‌بخشی','مواد اولیه / محصولات / قطعات — با حد هشدار')+'<div class="seg"><button data-c="raw" class="'+(cat=='raw'?'on':'')+'">🌿 مواد اولیه</button><button data-c="prod" class="'+(cat=='prod'?'on':'')+'">🛢 محصولات</button><button data-c="part" class="'+(cat=='part'?'on':'')+'">🔧 قطعات</button></div><div class="panel"><h3>افزودن / به‌روزرسانی</h3><div class="fgrid"><input class="inp" id="iN" placeholder="نام کالا"><input class="inp" type="number" id="iQ" placeholder="موجودی"><input class="inp" id="iU" placeholder="واحد (kg/لیتر/عدد)"><input class="inp" type="number" id="iM" placeholder="حد هشدار"></div><button class="fbtn" id="iAdd">ذخیره</button></div><div class="panel"><h3>موجودی‌ها</h3><div class="tbw"><table><tr><th>کالا</th><th>موجودی</th><th>واحد</th><th>حد هشدار</th><th>وضعیت</th></tr>'+rows+'</table></div></div>';
$$('#main .seg button').forEach(function(b){b.onclick=function(){cat=b.getAttribute('data-c');draw()}});
$('#iAdd').onclick=function(){var n=$('#iN').value.trim();if(!n){toast('نام کالا را وارد کن.',1);return}var inv2=D('pp_inv',[]),ex=null;for(var j=0;j<inv2.length;j++){if(inv2[j].c===cat&&inv2[j].n===n){ex=inv2[j];break}}var it={c:cat,n:n,q:+$('#iQ').value\vert{}\vert{}0,u:$('#iU').value.trim()||'kg',m:+$('#iM').value||0};if(ex){ex.q=it.q;ex.u=it.u;ex.m=it.m}else inv2.push(it);SV('pp_inv',inv2);toast('انبار به‌روزرسانی شد.');draw()}}
draw()};
RENDER.batch=function(){var bs=D('pp_batches',[]),b=null;for(var i=0;i<bs.length;i++){if(bs[i].st!=='done'){b=bs[i];break}}
var CHK=[['وضعیت راکتور',1],['آب‌بندی و درب',1],['اتصالات',1],['مخزن ضدانفجار',1],['مسیر خروجی گاز',1],['کندانسور',1],['مشعل‌ها',1],['برق و کنترل',1],['سایر',0]];
var canStart=['admin','supervisor','factory'].indexOf(S.user.role)>=0;
function draw(){var html=head('Batch و چرخه پخت','ایجاد → چک‌لیست → Start → پایان پخت → Cooling → تخلیه');
if(!b){var mats=D('pp_mat',['لاستیک','پلاستیک']);
html+='<div class="panel"><h3>ایجاد Batch جدید</h3><div class="fgrid"><input class="inp" id="nR" placeholder="راکتور (R-01)"><select class="inp" id="nM">'+mats.map(function(m){return'<option>'+esc(m)+'</option>'}).join('')+'</select><input class="inp" type="number" id="nT" placeholder="تناژ (تن)"><input class="inp" type="number" id="nS" placeholder="شیفت (A/B/C)"></div><button class="fbtn" id="nAdd">ایجاد Batch</button></div>'}
else{var chk=b.chk||CHK.map(function(){return false}),lock=false;for(var k=0;k<CHK.length;k++){if(CHK[k][1]&&!chk[k]){lock=true;break}}
html+='<div class="panel"><h3>Batch فعال: '+esc(b.id)+' — '+esc(b.m)+'</h3><div class="tbw"><table><tr><th>✔</th><th>مورد کنترل</th><th>نوع</th></tr>';
for(var j=0;j<CHK.length;j++){html+='<tr><td><input type="checkbox" class="tick" data-i="'+j+'" '+(chk[j]?'checked':'')+'></td><td style="text-align:right">'+CHK[j][0]+'</td><td>'+(CHK[j][1]?'<span class="badc">بحرانی</span>':'<span style="color:#7d9bbd">عادی</span>')+'</td></tr>'}
html+='</table></div>'+ (lock?'<div class="stbox st-lock">🔴 START LOCKED — آیتم‌های بحرانی را تیک بزن</div>':'<div class="stbox st-open">🟢 START UNLOCKED</div>');
var stTxt={created:'چک‌لیست را کامل کن',running:'🔥 راکتور در کار — ثبت ساعتی از منو',cooling:'❄️ Cooling — دمای مجاز تخلیه تا ۵۰ درجه',unload:'📤 خروجی‌ها را ثبت کن'};
html+='<p class="muted2">'+(stTxt[b.st]||'')+'</p>';
if(b.st=='created'&&canStart)html+='<button class="fbtn" id="stGo">🔥 START REACTOR</button>';
if(b.st=='running')html+='<button class="fbtn warn" id="stEnd">🛑 پایان پخت → Cooling</button>';
if(b.st=='cooling'&&canStart)html+='<div class="fgrid" style="margin-top:10px"><input class="inp" type="number" id="cT" placeholder="دمای کنونی (°C)"></div><button class="fbtn" id="stCool">✅ تأیید دمای مجاز</button>';
if(b.st=='unload')html+='<div class="panel" style="margin-top:12px"><h3>ثبت خروجی</h3><div class="fgrid"><input class="inp" type="number" id="oOil" placeholder="روغن (لیتر)"><input class="inp" type="number" id="oCar" placeholder="کربن بلک (kg)"><input class="inp" type="number" id="oWire" placeholder="سیم (kg)"><input class="inp" type="number" id="oWst" placeholder="ضایعات (kg)"></div><button class="fbtn" id="oAdd">ثبت و اتمام Batch</button></div>';
html+='</div>'}
var hist=bs.slice().reverse().map(function(x){var st={created:'📋',running:'🔥 در کار',cooling:'❄️ Cooling',unload:'📤 تخلیه',done:'✅ تمام'}[x.st]||x.st;return'<tr><td dir="ltr"><b>'+esc(x.id)+'</b></td><td>'+esc(x.m)+'</td><td dir="ltr">'+fa(x.t)+' تن</td><td>'+esc(x.op)+'</td><td>'+st+'</td><td dir="ltr">'+(x.o2?fa(x.o2)+' L':'—')+'</td></tr>'}).join('');
html+='<div class="panel"><h3>تاریخچه Batchها</h3><div class="tbw"><table><tr><th>شناسه</th><th>خوراک</th><th>تناژ</th><th>اپراتور</th><th>وضعیت</th><th>روغن</th></tr>'+hist+'</table></div></div>';
$('#main').innerHTML=html;
$$('#main .tick').forEach(function(t){t.onchange=function(){var nt=$$('#main .tick');b.chk=CHK.map(function(c,k){return nt[k].checked});SV('pp_batches',bs);draw()}});
var n=$('#nAdd');if(n)n.onclick=function(){var t=+$('#nT').value;if(!t){toast('تناژ را وارد کن.',1);return}bs.push({id:'B-'+today().replace(/-/g,'').slice(2)+'-'+String(Date.now()).slice(-3),m:$('#nM').value,t:t,op:S.user.name,sh:$('#nS').value||'A',d:today(),st:'created',chk:CHK.map(function(){return false})});SV('pp_batches',bs);toast('Batch ایجاد شد.');draw()};
var g=$('#stGo');if(g)g.onclick=function(){b.st='running';b.start=now();SV('pp_batches',bs);toast('🔥 استارت شد — ثبت ساعتی آغاز شود');draw()};
var e=$('#stEnd');if(e)e.onclick=function(){b.st='cooling';b.cook=now();SV('pp_batches',bs);toast('پایان پخت — Cooling');draw()};
var c=$('#stCool');if(c)c.onclick=function(){var t=+$('#cT').value;if(t>50){toast('دمای مجاز تا ۵۰ است. الان: '+t,1);return}b.st='unload';SV('pp_batches',bs);toast('آماده تخلیه ✅');draw()};
var o=$('#oAdd');if(o)o.onclick=function(){var oil=+$('#oOil').value||0,car=+$('#oCar').value\vert{}\vert{}0,wr=+$('#oWire').value||0;if(!oil&&!car){toast('خروجی را وارد کن.',1);return}b.o2=oil;b.c2=car;b.w2=wr;b.st='done';b.end=now();
var inv=D('pp_inv',[]);function add(n2,q,u){if(!q)return;var f2=null;for(var z=0;z<inv.length;z++){if(inv[z].c==='prod'&&inv[z].n===n2){f2=inv[z];break}}if(f2)f2.q=+f2.q+q;else inv.push({c:'prod',n:n2,q:q,u:u,m:0})}
add('روغن',oil,'لیتر');add('کربن بلک',car,'kg');add('سیم',wr,'kg');SV('pp_inv',inv);toast('خروجی ثبت شد — انبار محصولات به‌روزرسانی شد ✅');draw()}}
draw()};
RENDER.log=function(){var bs=D('pp_batches',[]),rb=null;for(var i=0;i<bs.length;i++){if(bs[i].st=='running'||bs[i].st=='cooling'){rb=bs[i];break}}
if(!rb){$('#main').innerHTML=head('ثبت ساعتی','')+'<div class="panel"><p>Batch فعالی نیست — اول از «Batch و چرخه پخت» استارت کن.</p></div>';return}
var sop=D('pp_sop',{a:220,b:270,c:320});function clr(t){return t>=sop.b?'badc':t>=sop.a?'warnc':'okc'}
var arr=D('pp_log',[]).filter(function(l){return l.bid===rb.id});
var rows=arr.map(function(r){return'<tr><td><b dir="ltr">'+r.t+'</b></td><td class="'+clr(r.r)+'" dir="ltr">'+fa(r.r)+'°</td><td dir="ltr">'+fa(r.c)+'</td><td dir="ltr">'+fa(r.p)+'</td><td dir="ltr">'+fa(r.b)+'/6</td><td class="okc">✓</td></tr>'}).join('');
$('#main').innerHTML=head('ثبت ساعتی — '+rb.id,'🟢 عادی · 🟠 ≥ '+sop.a+'° · 🔴 ≥ '+sop.b+'°')+'<div class="panel"><h3>رکورد جدید</h3><div class="fgrid"><input class="inp" id="lT" value="'+now()+'"><input class="inp" type="number" id="lR" placeholder="دمای راکتور °C"><input class="inp" type="number" id="lC" placeholder="کندانسور °C"><input class="inp" type="number" id="lP" placeholder="فشار Bar"><input class="inp" type="number" id="lB" placeholder="مشعل فعال (تا ۶)"><input class="inp" id="lN" placeholder="توضیح"></div><button class="fbtn" id="lAdd">ثبت رکورد</button></div><div class="panel"><h3>رکوردها ('+fa(arr.length)+')</h3><div class="tbw"><table><tr><th>ساعت</th><th>راکتور</th><th>کندانسور</th><th>فشار</th><th>مشعل</th><th></th></tr>'+rows+'</table></div></div>';
$('#lAdd').onclick=function(){if($('#lR').value===''){toast('دمای راکتور را وارد کن.',1);return}var all=D('pp_log',[]);all.push({bid:rb.id,t:$('#lT').value,r:+$('#lR').value,c:+$('#lC').value\vert{}\vert{}0,p:+$('#lP').value||0,b:+$('#lB').value\vert{}\vert{}0,n:$('#lN').value});SV('pp_log',all);toast('ثبت شد ✅');RENDER.log()}};
RENDER.sales=function(){var inv=D('pp_inv',[]),prods=inv.filter(function(i){return i.c==='prod'&&+i.q>0}),sl=D('pp_sales',[]);
var due=sl.reduce(function(s,x){return s+(+x.q*+x.p-+x.paid)},0);
var rows=sl.slice().reverse().map(function(x){var m=x.q*x.p,rem=m-x.paid;return'<tr><td>'+esc(x.d)+'</td><td>'+esc(x.cu)+'</td><td>'+esc(x.pr)+'</td><td dir="ltr">'+fmt(x.q)+'</td><td dir="ltr">'+fmt(m)+'</td><td class="okc" dir="ltr">'+fmt(x.paid)+'</td><td class="'+(rem>0?'badc':'okc')+'" dir="ltr">'+fmt(rem)+'</td></tr>'}).join('');
$('#main').innerHTML=head('فروش','فروش → کسر موجودی + درآمد + مطالبات')+'<div class="panel"><h3>ثبت فروش</h3><div class="fgrid"><input class="inp" type="date" id="sD" value="'+today()+'"><input class="inp" id="sC" placeholder="مشتری"><select class="inp" id="sP">'+(prods.length?prods.map(function(p){return'<option>'+esc(p.n)+'</option>'}).join(''):'<option>— محصولی نیست —</option>')+'</select></div><div class="fgrid"><input class="inp" type="number" id="sQ" placeholder="مقدار"><input class="inp" type="number" id="sPr" placeholder="قیمت هر واحد (ریال)"><input class="inp" type="number" id="sPd" placeholder="دریافت‌شده (ریال)"></div><button class="fbtn" id="sAdd">ثبت فروش</button><p class="muted2">مطالبات وصول‌نشده: <b>'+fmt(due)+'</b> ریال</p></div><div class="panel"><h3>فروش‌ها</h3><div class="tbw"><table><tr><th>تاریخ</th><th>مشتری</th><th>محصول</th><th>مقدار</th><th>کل</th><th>دریافتی</th><th>مانده</th></tr>'+rows+'</table></div></div>';
$('#sAdd').onclick=function(){var pn=$('#sP').value,q=+$('#sQ').value,pr=+$('#sPr').value,paid=+$('#sPd').value||0;if(!q||!pr||pn.indexOf('—')==0){toast('مقدار و قیمت را وارد کن.',1);return}
var p=null;for(var z=0;z<inv.length;z++){if(inv[z].c==='prod'&&inv[z].n===pn){p=inv[z];break}}if(!p||q>+p.q){toast('موجودی کافی نیست.',1);return}
p.q=+p.q-q;SV('pp_inv',inv);sl.push({d:$('#sD').value,cu:$('#sC').value.trim()||'—',pr:pn,q:q,p:pr,paid:paid});SV('pp_sales',sl);
var fin=D('pp_fin',[]);fin.push({d:$('#sD').value,t:'in',de:'فروش '+pn+' → '+($('#sC').value.trim()||'مشتری'),a:paid});SV('pp_fin',fin);toast('فروش ثبت شد ✅');RENDER.sales()}};
RENDER.fin=function(){var fin=D('pp_fin',[]);
var inc=fin.reduce(function(s,f){return s+(f.t=='in'?+f.a:0)},0),exp=fin.reduce(function(s,f){return s+(f.t=='out'?+f.a:0)},0);
var rows=fin.slice().reverse().map(function(f){return'<tr><td>'+esc(f.d)+'</td><td>'+(f.t=='in'?'<span class="okc">درآمد</span>':'<span class="badc">هزینه</span>')+'</td><td style="text-align:right">'+esc(f.de)+'</td><td dir="ltr">'+fmt(f.a)+'</td></tr>'}).join('');
$('#main').innerHTML=head('امور مالی','درآمد − هزینه = سود')+'<div class="kpis"><div class="kpi k-green"><i>📈</i><div><h5>درآمد</h5><div class="v">'+fmt(inc)+'</div></div></div><div class="kpi k-org"><i>📉</i><div><h5>هزینه</h5><div class="v">'+fmt(exp)+'</div></div></div><div class="kpi '+(inc-exp>=0?'k-green':'k-red')+'"><i>💎</i><div><h5>سود خالص</h5><div class="v">'+fmt(inc-exp)+'</div></div></div></div><div class="panel"><h3>ثبت دستی</h3><div class="fgrid"><select class="inp" id="fT"><option value="in">درآمد</option><option value="out">هزینه</option></select><input class="inp" type="date" id="fD" value="'+today()+'"><input class="inp" id="fDe" placeholder="شرح"><input class="inp" type="number" id="fA" placeholder="مبلغ (ریال)"></div><button class="fbtn" id="fAdd">ثبت</button></div><div class="panel"><h3>دفتر تراکنش‌ها</h3><div class="tbw"><table><tr><th>تاریخ</th><th>نوع</th><th>شرح</th><th>مبلغ</th></tr>'+rows+'</table></div></div>';
$('#fAdd').onclick=function(){var a=+$('#fA').value;if(!a){toast('مبلغ را وارد کن.',1);return}fin.push({d:$('#fD').value,t:$('#fT').value,de:$('#fDe').value.trim()||'—',a:a});SV('pp_fin',fin);toast('ثبت شد ✅');RENDER.fin()}};
RENDER.tm=function(){var inv=D('pp_inv',[]),parts=inv.filter(function(i){return i.c==='part'}),arr=D('pp_tm',[]);
var rows=arr.slice().reverse().map(function(x){return'<tr><td>'+esc(x.d)+'</td><td dir="ltr">'+esc(x.e)+'</td><td>'+esc(x.p)+'</td><td dir="ltr">'+fa(x.q)+'</td><td>'+esc(x.w)+'</td><td dir="ltr">'+fmt(x.c)+'</td></tr>'}).join('');
$('#main').innerHTML=head('تعمیرات و نگهداری','مصرف قطعه → کسر انبار × هزینه مالی')+'<div class="panel"><h3>ثبت تعمیر</h3><div class="fgrid"><input class="inp" type="date" id="tD" value="'+today()+'"><input class="inp" id="tE" value="R-01"><select class="inp" id="tP">'+(parts.length?parts.map(function(p){return'<option>'+esc(p.n)+'</option>'}).join(''):'<option value="">— قطعه‌ای نیست —</option>')+'</select></div><div class="fgrid"><input class="inp" type="number" id="tQ" placeholder="تعداد"><input class="inp" id="tW" placeholder="تعمیرکار"><input class="inp" type="number" id="tC" placeholder="هزینه (ریال)"></div><input class="inp" id="tX" placeholder="شرح کار"><button class="fbtn" id="tAdd">ثبت</button></div><div class="panel"><h3>سابقه</h3><div class="tbw"><table><tr><th>تاریخ</th><th>تجهیز</th><th>قطعه</th><th>تعداد</th><th>نیرو</th><th>هزینه</th></tr>'+rows+'</table></div></div>';
$('#tAdd').onclick=function(){var q=+$('#tQ').value||0,c=+$('#tC').value\vert{}\vert{}0,pn=$('#tP').value;
if(pn&&q){var f2=null;for(var z=0;z<inv.length;z++){if(inv[z].c==='part'&&inv[z].n===pn){f2=inv[z];break}}if(!f2||+f2.q<q){toast('موجودی قطعه کافی نیست.',1);return}f2.q=+f2.q-q;SV('pp_inv',inv)}
arr.push({d:$('#tD').value,e:$('#tE').value.trim()||'—',p:pn||'—',q:q,w:$('#tW').value.trim()\vert{}\vert{}S.user.name,c:c,x:$('#tX').value});SV('pp_tm',arr);
if(c){var fin=D('pp_fin',[]);fin.push({d:$('#tD').value,t:'out',de:'تعمیر '+($('#tE').value||''),a:c});SV('pp_fin',fin)}
toast('ثبت شد 🔧');RENDER.tm()}};
RENDER.users=function(){var us=D('pp_users',[]);
var rows=us.map(function(u,i){return'<tr><td>'+esc(u.name)+'</td><td dir="ltr">'+esc(u.email)+'</td><td>'+(ROLES[u.role]?ROLES[u.role][1]+' '+ROLES[u.role][0]:u.role)+'</td><td><select class="rolesel" data-i="'+i+'">'+Object.keys(ROLES).map(function(k){return'<option value="'+k+'" '+(u.role===k?'selected':'')+'>'+ROLES[k][1]+' '+ROLES[k][0]+'</option>'}).join('')+'</select></td></tr>'}).join('');
$('#main').innerHTML=head('کاربران و نقش‌ها','نقش هر نفر را انتخاب و ذخیره کن')+'<div class="panel"><div class="tbw"><table><tr><th>نام</th><th>ایمیل</th><th>نقش</th><th>تغییر نقش</th></tr>'+rows+'</table></div><button class="fbtn" id="uSave" style="margin-top:12px">💾 ذخیره نقش‌ها</button></div>';
$('#uSave').onclick=function()
