'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const D=(k,d)=>{try{const v=JSON.parse(localStorage.getItem(k));return v==null?d:v}catch(e){return d}};
const SV=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const fa=s=>String(s).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);
const fmt=n=>fa(Number(n\vert{}\vert{}0).toLocaleString('en-US'));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toISOString().slice(0,10);
const now=()=>new Date().toTimeString().slice(0,5);
function toast(m,e){const t=document.createElement('div');t.className='toast'+(e?' error':'');t.textContent=m;$('#tw').appendChild(t);requestAnimationFrame(()=>t.classList.add('show'));setTimeout(()=>{t.classList.remove('show');setTimeout(()=>t.remove(),350)},3000)}
const hsh=t=>crypto.subtle.digest('SHA-256',new TextEncoder().encode(t)).then(b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join(''));
const S={user:null};
const ROLES={admin:['مدیر کل','👑'],factory:['مدیر کارخانه','🧭'],supervisor:['مسئول شیفت','🛡️'],operator:['اپراتور','👷'],warehouse:['انباردار','📦'],finance:['مالی','💰'],maint:['تعمیرکار','🔧'],viewer:['ناظر — بی‌دسترسی','👁️']};
const A={dash:'all',flow:'all',batch:'op',log:'op',buy:'wh',inv:'wh',sales:'fin',fin:'fin',tm:'mt',users:'ad',settings:'ad'};
const ACC={op:['admin','factory','supervisor','operator'],wh:['admin','factory','warehouse'],fin:['admin','factory','finance'],mt:['admin','factory','maint'],ad:['admin']};
const MENU=[['🏠 اصلی',[['dash','📊 داشبورد'],['flow','⚡ جریان فرآیند']]],['🔥 پخت و تولید',[['batch','🔥 Batch و چرخه پخت'],['log','🕐 ثبت ساعتی فرآیند']]],['📦 عملیات و انبار',[['buy','🛒 خرید مواد اولیه'],['inv','📦 انبار سه‌بخشی']]],['💰 مالی و فروش',[['sales','🧾 فروش'],['fin','💳 امور مالی']]],['🔧 پشتیبانی',[['tm','🔧 تعمیرات و PM']]],['⚙️ مدیریت',[['users','👥 کاربران و نقش‌ها'],['settings','⚙️ تنظیمات و SOP']]]];
const can=id=>{const a=A[id];return a==='all'\vert{}\vert{}ACC[a].includes(S.user.role)};
const head=(t,s)=>'<div class="vhead"><h2>'+t+'</h2><p>'+s+'</p></div>';
let mode='login';
function tabUI(m){mode=m;$('#tLogin').classList.toggle('on',m==='login');$('#tReg').classList.toggle('on',m==='register');$('#gName').classList.toggle('hidden',m!=='register');$('#gPass2').classList.toggle('hidden',m!=='register');$('#goBtn').textContent=m==='login'?'ورود به سامانه':'ایجاد حساب';['eE','eP','eP2','eTop'].forEach(i=>$('#'+i).textContent='')}
$('#tLogin').onclick=()=>tabUI('login');$('#tReg').onclick=()=>tabUI('register');
$('#goBtn').onclick=async()=>{const em=$('#qEmail').value.trim().toLowerCase(),p=$('#qPass').value;let ok=1;const E=(i,m)=>{$('#'+i).textContent=m;if(m)ok=0};E('eE',/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(em)?'':'ایمیل معتبر نیست.');E('eP',p.length<6?'رمز حداقل ۶ کاراکتر.':'');if(mode==='register'&&$('#qPass2').value!==p){E('eP2','تکرار رمز مطابقت ندارد.');ok=0}if(!ok)return;const us=D('pp_users',[]),h=await hsh(p);
if(mode==='register'){if(us.some(x=>x.email===em)){$('#eE').textContent='این ایمیل قبلاً ثبت شده است.';return}const role=us.length?'viewer':'admin';const u={name:$('#qName').value.trim()\vert{}\vert{}em.split('@')[0],email:em,hash:h,role};us.push(u);SV('pp_users',us);localStorage.setItem('pp_session',em);start(u);toast(role==='admin'?'شما مدیر کل سیستم هستید 👑':'ثبت‌نام شدید — نقش شما «ناظر» است؛ مدیر نقش شما را تعیین می‌کند.')}
else{const u=us.find(x=>x.email===em&&x.hash===h);if(!u){$('#eTop').textContent='ایمیل یا رمز اشتباه است. اگر حساب ندارید ثبت‌نام کنید.';return}localStorage.setItem('pp_session',em);start(u);toast('خوش آمدید '+u.name)}};
$('#outBtn').onclick=()=>{localStorage.removeItem('pp_session');location.reload()};
function start(u){if(!ROLES[u.role])u.role='viewer';S.user=u;$('#gate').classList.add('hidden');$('#app').classList.remove('hidden');$('#uName').textContent=u.name;$('#uRole').textContent=ROLES[u.role][1]+' '+ROLES[u.role][0];renderAside();go('dash')}
function renderAside(){$('#aside').innerHTML=MENU.map(([g,items])=>{const ok=items.filter(i=>can(i[0]));return ok.length?'<div class="grp"><h4>'+g+'</h4>'+ok.map(i=>'<button class="sitem" data-v="'+i[0]+'">'+i[1]+'</button>').join('')+'</div>':''}).join('');$$('#aside .sitem').forEach(b=>b.onclick=()=>go(b.dataset.v))}
const RENDER={};
function go(id){S.view=id;$$('#aside .sitem').forEach(b=>b.classList.toggle('on',b.dataset.v===id));RENDER[id]()}
RENDER.flow=function(){$('#main').innerHTML=head('جریان کامل فرآیند','از خرید تا فروش و سود');const F=[['🛒','خرید'],['⚖️','توزین'],['🧰','آماده‌سازی'],['📋','چک‌لیست'],['▶️','Start'],['📈','ثبت ساعتی'],['⚠️','بازه بحرانی'],['🔥','Cracking'],['🛢','روغن‌گیری'],['⏹','خاموشی'],['❄️','Cooling'],['📤','تخلیه'],['🧾','ثبت خروجی'],['💰','فروش'],['📊','سود']];$('#main').innerHTML+='<div class="panel"><div class="flow">'+F.map((f,i)=>'<div class="fs"><div class="fi" style="animation-delay:'+(i*.15)+'s">'+f[0]+'</div><span>'+f[1]+'</span></div>'+(i<F.length-1?'<div class="far">➜</div>':'')).join('')+'</div></div>'};
RENDER.dash=function(){const bs=D('pp_batches',[]),fin=D('pp_fin',[]),sls=D('pp_sales',[]),inv=D('pp_inv',[]);
const act=bs.filter(b=>b.st!=='done').length,oil=bs.filter(b=>b.st==='done').reduce((s,b)=>s+ +b.o2,0);
const inc=fin.filter(f=>f.t==='in').reduce((s,f)=>s+ +f.a,0),exp=fin.filter(f=>f.t==='out').reduce((s,f)=>s+ +f.a,0);
const rec=sls.reduce((s,x)=>s+(x.q*x.p-x.paid),0),low=inv.filter(i=>+i.q<+i.m).length;
$('#main').innerHTML=head('داشبورد','نقش شما: '+ROLES[S.user.role][0])+'<div class="kpis">'+
'<div class="kpi k-blue"><i>🔥</i><div><h5>Batch در جریان</h5><div class="v">'+fa(act)+'</div></div></div>'+
'<div class="kpi k-pur"><i>🛢</i><div><h5>روغن تولیدی (لیتر)</h5><div class="v">'+fmt(oil)+'</div></div></div>'+
'<div class="kpi k-green"><i>💰</i><div><h5>درآمد کل (ریال)</h5><div class="v">'+fmt(inc)+'</div></div></div>'+
'<div class="kpi k-org"><i>📉</i><div><h5>هزینه کل (ریال)</h5><div class="v">'+fmt(exp)+'</div></div></div>'+
'<div class="kpi '+(rec>0?'k-red':'k-green')+'"><i>🧾</i><div><h5>مطالبات وصول‌نشده</h5><div class="v">'+fmt(rec)+'</div></div></div>'+
'<div class="kpi '+(low?'k-red':'k-blue')+'"><i>📦</i><div><h5>هشدار موجودی انبار</h5><div class="v">'+fa(low)+'</div></div></div></div>'+
'<div class="panel"><h3>راهنمای دسترسی نقش شما</h3><div style="font-size:13px;line-height:2.2">'+(S.user.role==='operator'?'👩‍🏭 اپراتور: داشبورد + چرخه پخت + ثبت ساعتی فرآیند — مالی/فروش/انبار مخفی است.':S.user.role==='warehouse'?'📦 انباردار: خرید مواد + انبار — مالی/فروش/پخت مخفی است.':S.user.role==='admin'?'👑 مدیر کل: دسترسی کامل + تعیین نقش کاربران در «کاربران و نقش‌ها».':'دسترسی‌های نقش شما در منو نمایش داده شده است.')+'</div><p class="muted2">👑 فقط مدیر کل مالی، فروش و کاربران را می‌بیند. هر بخش صفحه مخصوص خودش را دارد.</p></div>'};
RENDER.buy=function(){const mats=D('pp_mat',['لاستیک','پلاستیک','روغن سوخته','گریس سوخته']),arr=D('pp_buy',[]);
$('#main').innerHTML=head('خرید و تأمین مواد اولیه','ثبت خرید → موجودی مواد اولیه + هزینه مالی')+'<div class="panel"><h3>ثبت خرید</h3><div class="fgrid"><input class="inp" type="date" id="bD" value="'+today()+'"><input class="inp" id="bSup" placeholder="تأمین‌کننده"><select class="inp" id="bM">'+mats.map(m=>'<option>'+esc(m)+'</option>').join('')+'</select></div><div class="fgrid"><input class="inp" type="number" id="bW" placeholder="وزن (kg)"><input class="inp" type="number" id="bP" placeholder="قیمت کل (ریال)"><input class="inp" type="number" id="bT" placeholder="حمل + تخلیه (ریال)"></div><button class="fbtn" id="bAdd">ثبت خرید</button><div class="muted2">بهای هر کیلو = (قیمت + حمل) ÷ وزن — محاسبه خودکار</div></div><div class="panel"><h3>خریدها ('+fa(arr.length)+')</h3><div class="tbw"><table><tr><th>تاریخ</th><th>تأمین‌کننده</th><th>ماده</th><th>وزن</th><th>هزینه</th><th>قیمت هر کیلو</th></tr>'+arr.map(r=>'<tr><td>'+esc(r.d)+'</td><td>'+esc(r.s)+'</td><td>'+esc(r.m)+'</td><td dir="ltr">'+fa(r.w)+'</td><td dir="ltr">'+fmt(+r.p+ +r.t)+'</td><td class="warnc" dir="ltr">'+fa((r.p+r.t)/r.w)+'</td></tr>').join('')+'</table></div></div>';
$('#bAdd').onclick=function(){const w=+$('#bW').value,p=+$('#bP').value,t=+$('#bT').value;if(!w\vert{}\vert{}!p){toast('وزن و قیمت را وارد کنید.',1);return}
const r={d:$('#bD').value,s:$('#bSup').value.trim()\vert{}\vert{}'—',m:$('#bM').value,w,p,t};arr.push(r);SV('pp_buy',arr);
const inv=D('pp_inv',[]);const it=inv.find(i=>i.c==='raw'&&i.n===r.m);if(it)it.q=+it.q+w;else inv.push({c:'raw',n:r.m,q:w,u:'kg',m:1000});SV('pp_inv',inv);
const fin=D('pp_fin',[]);fin.push({d:r.d,t:'out',de:'خرید '+r.m+' از '+r.s,a:p+t});SV('pp_fin',fin);
toast('خرید ثبت شد؛ موجودی مواد و هزینه مالی به‌روزرسانی شد.');RENDER.buy()}};
RENDER.inv=function(){const CAT={raw:'🌿 مواد اولیه',prod:'🛢 محصولات نهایی',part:'🔧 قطعات یدکی'};let cat='raw';
function draw(){$('#main').innerHTML=head('انبار','سه بخش: مواد اولیه / محصولات / قطعات — هر کالا با حداقل موجودی')+'<div class="seg"><button data-c="raw" class="'+(cat==='raw'?'on':'')+'">🌿 مواد اولیه</button><button data-c="prod" class="'+(cat==='prod'?'on':'')+'">🛢 محصولات</button><button data-c="part" class="'+(cat==='part'?'on':'')+'">🔧 قطعات</button></div><div class="panel"><h3>افزودن / به‌روزرسانی</h3><div class="fgrid"><input class="inp" id="iN" placeholder="نام کالا"><input class="inp" type="number" id="iQ" placeholder="موجودی"><input class="inp" id="iU" placeholder="واحد (kg / لیتر / عدد)"><input class="inp" type="number" id="iM" placeholder="حد هشدار"></div><button class="fbtn" id="iAdd">ذخیره</button></div><div class="panel"><h3>موجودیها</h3><div class="tbw"><table><tr><th>کالا</th><th>موجودی</th><th>واحد</th><th>حد هشدار</th><th>وضعیت</th></tr>'+D('pp_inv',[]).filter(i=>i.c===cat).map(i=>'<tr><td>'+esc(i.n)+'</td><td dir="ltr">'+fmt(i.q)+'</td><td>'+esc(i.u)+'</td><td dir="ltr">'+fmt(i.m)+'</td><td class="'+(+i.q<+i.m?'badc":"okc')+'">'+(+i.q<+i.m?'کمبود!':'موجود')+'</td>'+tr()+'</tr>').join('')+'</table></div></div>';
$$('#main .seg button').forEach(b=>b.onclick=()=>{cat=b.dataset.c;draw()});
$('#iAdd').onclick=function(){const n=$('#iN').value.trim();if(!n){toast('نام کالا را وارد کنید.',1);return}const inv=D('pp_inv',[]);const ex=inv.find(i=>i.c===cat&&i.n===n);const it={c:cat,n,q:+$('#iQ').value\vert{}\vert{}0,u:$('#iU').value.trim()||'kg',m:+$('#iM').value||0};if(ex)Object.assign(ex,it);else inv.push(it);SV('pp_inv',inv);toast('انبار به‌روزرسانی شد.');draw()}}draw()};
RENDER.batch=function(){const bs=D('pp_batches',[]),b=bs.find(x=>x.st!=='done');
const CHK=[['وضعیت راکتور',1],['آب‌بندی و درب',1],['اتصالات',1],['مخزن ضدانفجار',1],['مسیر خروجی',1],['کندانسور',1],['وضعیت مشعل‌ها',1],['برق و کنترل',1],['سایر موارد',0]];
const canStart=['admin','supervisor','factory'].includes(S.user.role);
function draw(){let html=head('Batch و چرخه پخت','ایجاد → چک‌لیست → Start → پایان پخت → Cooling → تخلیه');
if(!b){html+='<div class="panel"><h3>ایجاد Batch جدید</h3><div class="fgrid"><input class="inp" id="nR" placeholder="راکتور (R-01)"><select class="inp" id="nM">'+D('pp_mat',['لاستیک','پلاستیک']).map(m=>'<option>'+esc(m)+'</option>').join('')+'</select><input class="inp" type="number" id="nT" placeholder="تناژ (تن)"><input class="inp" id="nO" value="'+esc(S.user.name)+'"><input class="inp" id="nS" placeholder="شیفت (A/B/C)"></div><button class="fbtn" id="nAdd">ایجاد Batch</button></div>'}
else{const chk=b.chk||CHK.map(()=>false);const lock=CHK.some((r,i)=>r[1]&&!chk[i]);
html+='<div class="panel"><h3>Batch فعال: '+esc(b.id)+' — '+esc(b.m)+' / '+fa(b.t)+' تن</h3><div class="tbw"><table><tr><th></th><th>مورد کنترل</th><th>نوع</th></tr>'+CHK.map((r,i)=>'<tr><td><input type="checkbox" class="tick" data-i="'+i+'" '+(chk[i]?'checked':'')+'></td><td style="text-align:right">'+r[0]+'</td><td>'+(r[1]?'<span class="tag-c">بحرانی</span>':'<span class="tag-n">عادی</span>')+'</td></tr>').join('')+'</table></div>';
const ST={created:'',running:'🔥 راکتور در حال کار — ثبت ساعتی از تب بعدی',cooling:'❄️ در حال Coolینگ — پس از رسیدن به دمای مجاز، تأیید تخلیه',unload:'📤 آماده ثبت خروجی'};
if(lock)html+='<div class="stbox st-lock">🔴 START LOCKED — آیتم بحرانی تأیید نشده</div>';
else html+='<div class="stbox st-open">🟢 START UNLOCKED</div>';
html+='<p class="muted2" style="margin-top:8px">'+(ST[b.st]||'')+'</p>';
if(b.st==='created'&&canStart)html+='<button class="fbtn" id="stGo">🔥 START REACTOR</button>';
if(b.st==='running'&&(canStart||S.user.role==='operator'))html+='<button class="fbtn warn" id="stEnd">🛑 پایان پخت → Cooling</button>';
if(b.st==='cooling'&&canStart)html+='<div class="fgrid" style="margin-top:10px"><input class="inp" type="number" id="cT" placeholder="دمای کنونی راکتور (°C)"></div><button class="fbtn" id="stCool">✅ تأیید رسیدن به دمای مجاز تخلیه</button>';
if(b.st==='unload')html+='<div class="panel" style="margin-top:12px"><h3>ثبت خروجی</h3><div class="fgrid"><input class="inp" type="number" id="oOil" placeholder="روغن (لیتر)"><input class="inp" type="number" id="oCar" placeholder="کربن بلک (kg)"><input class="inp" type="number" id="oWire" placeholder="سیم (kg)"><input class="inp" type="number" id="oWst" placeholder="ضایعات (kg)"></div><button class="fbtn" id="oAdd">ثبت و اتمام Batch</button></div>';
html+='</div>'}
html+='<div class="panel"><h3>تاریخچه Batchها</h3><div class="tbw"><table><tr><th>شناسه</th><th>خوراک</th><th>تناژ</th><th>اپراتور</th><th>وضعیت</th><th>روغن</th></tr>'+bs.slice().reverse().map(x=>'<tr><td dir="ltr"><b>'+esc(x.id)+'</b></td><td>'+esc(x.m)+'</td><td dir="ltr">'+fa(x.t)+'</td><td>'+esc(x.op)+'</td><td>'+({created:'📋 چک‌لیست',running:'🔥 در حال کار',cooling:'❄️ Cooling',unload:'📤 تخلیه',done:'✅ تمام شد'}[x.st])+'</td><td dir="ltr">'+(x.o2?fa(x.o2):'—')+'</td></tr>').join('')+'</table></div></div>';
$('#main').innerHTML=html;
$$('#main .tick').forEach(t=>t.onchange=()=>{b.chk=CHK.map((r,i)=>$$('#main .tick')[i].checked);SV('pp_batches',bs);draw()});
if($('#nAdd'))$('#nAdd').onclick=()=>{const t=+$('#nT').value;if(!t){toast('تناژ را وارد کنید.',1);return}bs.push({id:'B-'+today().replace(/-/g,'').slice(2)+'-'+Date.now().toString().slice(-3),m:$('#nM').value,t,op:$('#nO').value\vert{}\vert{}S.user.name,sh:$('#nS').value||'A',d:today(),st:'created',chk:CHK.map(()=>false)});SV('pp_batches',bs);toast('Batch ایجاد شد — چک‌لیست را تکمیل کنید.');draw()};
if($('#stGo'))$('#stGo').onclick=()=>{b.st='running';b.start=now();SV('pp_batches',bs);toast('🔥 راکتور استارت شد — ثبت ساعتی آغاز شود.');draw()};
if($('#stEnd'))$('#stEnd').onclick=()=>{b.st='cooling';b.cook=now();SV('pp_batches',bs);toast('پایان پخت ثبت شد — Cooling آغاز شد.');draw()};
if($('#stCool'))$('#stCool').onclick=()=>{const t=+$('#cT').value;if(t>50){toast('دمای مجاز تخلیه ≤ 50°C است. الان: '+t,1);return}b.st='unload';SV('pp_batches',bs);toast('آماده تخلیه ✅');draw()};
if($('#oAdd'))$('#oAdd').onclick=()=>{const oil=+$('#oOil').value\vert{}\vert{}0,car=+$('#oCar').value||0,wr=+$('#oWire').value||0;if(!oil&&!car){toast('خروجی را وارد کنید.',1);return}Object.assign(b,{o2:oil,c2:car,w2:wr,st:'done',end:now()});
const inv=D('pp_inv',[]);const add=(n,q,u)=>{const it=inv.find(i=>i.c==='prod'&&i.n===n);if(it)it.q=+it.q+q;else inv.push({c:'prod',n,q,u,m:0})};add('روغن',oil,'لیتر');add('کربن بلک',car,'kg');add('سیم',wr,'kg');SV('pp_inv',inv);toast('خروجی ثبت و انبار محصولات به‌روزرسانی شد ✅');draw()}}draw()};
RENDER.log=function(){const bs=D('pp_batches',[]),rb=bs.find(x=>x.st==='running'||x.st==='cooling');const sop=D('pp_sop',{a:220,b:270,c:320});
if(!rb){$('#main').innerHTML=head('ثبت ساعتی فرآیند','')+'<div class="panel"><p>هیچ Batch در حال کار/cooling وجود ندارد — ابتدا از تب Batch استارت کنید.</p></div>';return}
const arr=D('pp_log',[]).filter(l=>l.bid===rb.id);
const clr=t=>t>=sop.c?'badc':t>=sop.b?'badc':t>=sop.a?'warnc':'okc';
$('#main').innerHTML=head('ثبت ساعتی — '+rb.id,'رنگ‌ها طبق SOP: سبک عادی / نارنجی ≥ '+sop.a+'° / قرمز ≥ '+sop.b+'°')+'<div class="panel"><h3>رکورد جدید</h3><div class="fgrid"><input class="inp" id="lT" value="'+now()+'"><input class="inp" type="number" id="lR" placeholder="دمای راکتور °C"><input class="inp" type="number" id="lC" placeholder="کندانسور °C"><input class="inp" type="number" id="lP" placeholder="فشار Bar"><input class="inp" type="number" id="lB" placeholder="مشعل‌های فعال (تا 6)"><input class="inp" id="lN" placeholder="توضیح اپراتور"></div><button class="fbtn" id="lAdd">ثبت رکورد</button></div><div class="panel"><h3>رکوردهای این Batch ('+fa(arr.length)+')</h3><div class="tbw"><table><tr><th>ساعت</th><th>راکتور</th><th>کندانسور</th><th>فشار</th><th>مشعل</th><th>وضعیت</th></tr>'+arr.map(r=>'<tr><td><b dir="ltr">'+r.t+'</b></td><td class="'+clr(r.r)+'" dir="ltr">'+fa(r.r)+'°C</td><td dir="ltr">'+fa(r.c)+'</td><td dir="ltr">'+fa(r.p)+'</td><td dir="ltr">'+fa(r.b)+'/6</td><td class="okc">ثبت ✓</td></tr>').join('')+'</table></div></div>';
$('#lAdd').onclick=()=>{const r=+$('#lR').value;if($('#lR').value===''){toast('دمای راکتور را وارد کنید.',1);return}arr.push({bid:rb.id,t:$('#lT').value,r,c:+$('#lC').value\vert{}\vert{}0,p:+$('#lP').value||0,b:+$('#lB').value\vert{}\vert{}0,n:$('#lN').value});const all=D('pp_log',[]);all.push(arr[arr.length-1]);SV('pp_log',all);toast('رکورد ساعتی ثبت شد ✅');RENDER.log()}};
RENDER.sales=function(){const prods=D('pp_inv',[]).filter(i=>i.c==='prod'&&i.q>0);
$('#main').innerHTML=head('فروش','فروش → کسر از موجودی + درآمد + مانده مطالبات')+'<div class="panel"><h3>ثبت فروش</h3><div class="fgrid"><input class="inp" type="date" id="sD" value="'+today()+'"><input class="inp" id="sC" placeholder="مشتری"><select class="inp" id="sP">'+(prods.length?prods.map(p=>'<option>'+esc(p.n)+'</option>').join(''):'<option value="">— محصولی نیست —</option>')+'</select><input class="inp" type="number" id="sQ" placeholder="مقدار '+(prods[0]?esc(prods[0].u):'')+'"><input class="inp" type="number" id="sPr" placeholder="قیمت هر واحد (ریال)"><input class="inp" type="number" id="sPd" placeholder="مبلغ دریافت‌شده (ریال)"></div><button class="fbtn" id="sAdd" '+(prods.length?'':'disabled style="opacity:.5"')+'>ثبت فروش</button></div><div class="panel"><h3>فروش‌ها و مطالبات</h3><div class="tbw"><table><tr><th>تاریخ</th><th>مشتری</th><th>محصول</th><th>مقدار</th><th>مبلغ کل</th><th>دریافتی</th><th>مانده</th></tr>'+D('pp_sales',[]).slice().reverse().map(x=>'<tr><td>'+esc(x.d)+'</td><td>'+esc(x.cu)+'</td><td>'+esc(x.pr)+'</td><td dir="ltr">'+fmt(x.q)+'</td><td dir="ltr">'+fmt(x.q*x.p)+'</td><td class="okc" dir="ltr">'+fmt(x.paid)+'</td><td class="'+(x.q*x.p-x.paid>0?'badc':'okc')+'" dir="ltr">'+fmt(x.q*x.p-x.paid)+'</td></tr>').join('')+'</table></div><p class="muted2">مطمعلات کل: <b>'+fmt(D('pp_sales',[]).reduce((s,x)=>s+(x.q*x.p-x.paid),0))+'</b> ریال</p></div>';
if(prods.length)$('#sAdd').onclick=()=>{const pn=$('#sP').value,q=+$('#sQ').value,pr=+$('#sPr').value,paid=+$('#sPd').value||0;const p=D('pp_inv',[]).find(i=>i.c==='prod'&&i.n===pn);
if(!q||!pr){toast('مقدار و قیمت را وارد کنید.',1);return}if(q>+p.q){toast('موجودی کافی نیست (موجودی: '+p.q+').',1);return}
p.q-=q;SV('pp_inv',D('pp_inv',[]));const sl=D('pp_sales',[]);sl.push({d:$('#sD').value,cu:$('#sC').value.trim()||'—',pr:pn,q,p,paid});SV('pp_sales',sl);
const fin=D('pp_fin',[]);fin.push({d:$('#sD').value,t:'in',de:'فروش '+pn+' به '+($('#sC').value||'مشتری')+' (وصولی)',a:paid});SV('pp_fin',fin);toast('فروش ثبت شد؛ موجودی کسر و درآمد ثبت شد ✅');RENDER.sales()}};
RENDER.fin=function(){const fin=D('pp_fin',[]);const inc=fin.filter(f=>f.t==='in').reduce((s,f)=>s+ +f.a,0),exp=fin.filter(f=>f.t==='out').reduce((s,f)=>s+ +f.a,0);
$('#main').innerHTML=head('امور مالی','درآمد − هزینه = سود عملیاتی')+'<div class="kpis"><div class="kpi k-green"><i>📈</i><div><h5>درآمد</h5><div class="v">'+fmt(inc)+'</div></div></div><div class="kpi k-org"><i>📉</i><div><h5>هزینه</h5><div class="v">'+fmt(exp)+'</div></div></div><div class="kpi '+(inc-exp>=0?'k-green':'k-red')+'"><i>💎</i><div><h5>سود خالص</h5><div class="v">'+fmt(inc-exp)+'</div></div></div></div><div class="panel"><h3>ثبت دستی</h3><div class="fgrid"><select class="inp" id="fT"><option value="in">درآمد</option><option value="out">هزینه</option></select><input class="inp" type="date" id="fD" value="'+today()+'"><input class="inp" id="fDe" placeholder="شرح (گازوئیل / حقوق / اجاره / سایر)"><input class="inp" type="number" id="fA" placeholder="مبلغ (ریال)"></div><button class="fbtn" id="fAdd">ثبت</button></div><div class="panel"><h3>دفتر تراکنش‌ها ('+fa(fin.length)+')</h3><div class="tbw"><table><tr><th>تاریخ</th><th>نوع</th><th>شرح</th><th>مبلغ</th></tr>'+fin.slice().reverse().map(f=>'<tr><td>'+esc(f.d)+'</td><td>'+(f.t==='in'?'<span class="okc">درآمد</span>':'<span class="badc">هزینه</span>')+'</td><td style="text-align:right">'+esc(f.de)+'</td><td dir="ltr">'+fmt(f.a)+'</td></tr>').join('')+'</table></div></div>';
$('#fAdd').onclick=()=>{const a=+$('#fA').value;if(!a){toast('مبلغ را وارد کنید.',1);return}fin.push({d:$('#fD').value,t:$('#fT').value,de:$('#fDe').value.trim()||'—',a});SV('pp_fin',fin);toast('ثبت شد ✅');RENDER.fin()}};
RENDER.tm=function(){const parts=D('pp_inv',[]).filter(i=>i.c==='part'),arr=D('pp_tm',[]);
$('#main').innerHTML=head('تعمیرات و نگهداری','مصرف قطعه → کسر انبار × هزینه مالی × سابقه تجهیز')+'<div class="panel"><h3>ثبت تعمیر</h3><div class="fgrid"><input class="inp" type="date" id="tD" value="'+today()+'"><input class="inp" id="tE" value="R-01"><select class="inp" id="tP">'+(parts.length?parts.map(p=>'<option>'+esc(p.n)+'</option>').join(''):'<option value="">— قطعه‌ای در انبار نیست —</option>')+'</select><input class="inp" type="number" id="tQ" placeholder="تعداد"><input class="inp" id="tW" placeholder="تعمیرکار"><input class="inp" type="number" id="tC" placeholder="هزینه کل (ریال)"></div><input class="inp" id="tX" placeholder="شرح کار"><button class="fbtn" id="tAdd">ثبت</button></div><div class="panel"><h3>سابقه تعمیرات</h3><div class="tbw"><table><tr><th>تاریخ</th><th>تجهیز</th><th>قطعه</th><th>تعداد</th><th>نیرو</th><th>هزینه</th></tr>'+arr.slice().reverse().map(x=>'<tr><td>'+esc(x.d)+'</td><td dir="ltr">'+esc(x.e)+'</td><td>'+esc(x.p)+'</td><td dir="ltr">'+fa(x.q)+'</td><td>'+esc(x.w)+'</td><td dir="ltr">'+fmt(x.c)+'</td></tr>').join('')+'</table></div></div>';
$('#tAdd').onclick=()=>{const q=+$('#tQ').value||0,c=+$('#tC').value\vert{}\vert{}0,pn=$('#tP').value;if(!pn&&!c){toast('قطعه یا هزینه را وارد کنید.',1);return}
if(pn&&q){const inv=D('pp_inv',[]);const pt=inv.find(i=>i.c==='part'&&i.n===pn);if(pt){if(+pt.q<q){toast('موجودی قطعه کافی نیست.',1);return}pt.q-=q;SV('pp_inv',inv)}}
arr.push({d:$('#tD').value,e:$('#tE').value,p:pn,q,w:$('#tW').value||S.user.name,c});SV('pp_tm',arr);
if(c){const fin=D('pp_fin',[]);fin.push({d:$('#tD').value,t:'out',de:'تعمیرات '+($('#tE').value||'')+' — '+(pn||''),a:c});SV('pp_fin',fin)}
toast('تعمیر ثبت شد؛ انبار و مالی به‌روزرسانی شد 🔧');RENDER.tm()}};
RENDER.users=function(){const us=D('pp_users',[]);
$('#main').innerHTML=head('کاربران و نقش‌ها','برای هر کاربر نقش را انتخاب کنید — دسترسی‌ها بلافاصله تغییر می‌کند')+'<div class="panel"><div class="tbw"><table><tr><th>نام</th><th>ایمیل</th><th>نقش فعلی</th><th>تغییر نقش</th></tr>'+us.map((u,i)=>'<tr><td>'+esc(u.name)+'</td><td dir="ltr">'+esc(u.email)+'</td><td>'+ROLES[u.role][1]+' '+ROLES[u.role][0]+'</td><td><select class="rolesel" data-i="'+i+'">'+Object.entries(ROLES).map(([k,v])=>'<option value="'+k+'" '+(u.role===k?'selected':'')+'>'+v[1]+' '+v[0]+'</option>').join('')+'</select></td></tr>').join('')+'</table></div><button class="fbtn" id="uSave" style="margin-top:12px">💾 ذخیره همه
